### ISSUE TITLE
No color on cached password

### ISSUE THREAD

**Issue by PerfectSlayer** [carmebar/unicornpass#2]
Hi,

In the case where you saved your password, the field are filled at the end of the page loading but background color is not displayed.
(As soon as you edit your password, the background is well displayed but not until you edit it.)

I don't know if it's in intended behavior or not ?

By the way, thanks for your add-on :wink: 

Regards.

**Comment by carmebar** [comment]
Thank you for your interest.

I think this should be the default behaviour.
There's not need to give the user the visual hint of the password since it's already correct and the browser filled it up for you.

I will think about adding the option to always colour the field for visual consistency.

Hope you're liking the add-on, cheers!

**Comment by PerfectSlayer** [comment]
Fine! Thanks.
